### ISSUE TITLE
"Pipeline is not in setup state" - unable to run multiple continuations

### ISSUE THREAD

**Issue by frm** [CircleCI-Public/continuation-orb#12]
## Orb version:

0.2.0

## What happened:

I have a monorepo with the following config:

```yaml
version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Determine the jobs to run
          command: OUTPUT_PATH=/tmp/workspace .circleci/scripts/diff.sh
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - pipeline-parameters.json

  service1:
    executor: continuation/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - continuation/continue:
          configuration_path: .circleci/service1.yml
          parameters: /tmp/workspace/pipeline-parameters.json

  service2:
    executor: continuation/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - continuation/continue:
          configuration_path: .circleci/service2.yml
          parameters: /tmp/workspace/pipeline-parameters.json

workflows:
  build:
    jobs:
      - setup
      - service1:
          requires:
            - setup
      - service2:
          requires:
            - setup

```

`setup` generates parameters to run on each of the two separate config.

Running `service1` triggers a new pipeline as expected. Running `service2` fails the continuation with `{"message":"Pipeline is not in setup state."}`

## Expected behavior:

Starting a new separate pipeline for each service being continued.

## Additional Information:

As an example, in my current scenario `.circleci/service1.yml` config file would be:

```yaml
version: 2.1

parameters:
  run-service1-build:
    type: boolean
    default: false
  run-service2-build:
    type: boolean
    default: false

jobs:
  test:
    # ...
  lint:
    # ...

workflows:
  test_and_lint:
    when: << pipeline.parameters.run-service1-build >>
    jobs:
      - lint
      - test
```

**Comment by shelbyd** [comment]
Can we get an update/discussion on this? This is blocking some work in our project.

**Comment by jackcbrown89** [comment]
@shelbyd I was facing this issue and re-running a pipeline from failed wasn't working. Starting a new pipeline worked for me, but I'm only using continuation once.

**Comment by BaptisteTamedia** [comment]
The issue is also here with the [path-filtering](https://circleci.com/developer/orbs/orb/circleci/path-filtering) orb.. Don't really see the interest if it's not able to run more than one job.

**Comment by xistz** [comment]
now that Github's reusable workflow is generally available, would like to see this for CircleCI too.

https://github.blog/2021-11-29-github-actions-reusable-workflows-is-generally-available/

**Comment by WayneYe** [comment]
1️⃣ 
This can be 100% reproducible from simply "Rerun workflow from start" for a setup-workflow.

**Comment by yibo-long** [comment]
Please provide feedback or update on this issue. The Dynamic Config's [documentation](https://circleci.com/docs/dynamic-config/#dynamic-config-faqs:~:text=Instead%20of%20using%20one%20full%20.circleci/config.yml%20file%2C%20you%20could%20use%20dynamic%20configuration%20to%20combine%20these%20individual%20fragments%20into%20a%20full%20configuration%20when%20a%20pipeline%20is%20triggered.%20This%20scenario%20can%20also%20be%20referred%20to%20as%20config%20splitting.) with multiple files support gave us a full wrong impression for how it works. Also there is a [finish.sh](https://github.com/CircleCI-Public/continuation-orb/blob/master/src/scripts/finish.sh) in the repo indicating it should accept multiple files by design, right?

**Comment by liamclarkedev** [comment]
Hello,

Thank you for raising this, the current limitation is that [a pipeline can only be continued once](https://circleci.com/docs/dynamic-config/#:~:text=A%20pipeline%20can%20only%20be%20continued%20once%20(that%20is%2C%20a%20pipeline%20cannot%20be%20continued%20with%20another%20setup%20configuration).), this is a security feature of dynamic config and is the expected behaviour of the `continuation-orb`. We will amend the documentation to remove the misleading information for supporting multiple continuations.

The [path-filtering-orb has recently added support](https://github.com/CircleCI-Public/path-filtering-orb/pull/72) for a separate config file per mapping, please use the latest version of the [CircleCI-Public/path-filtering-orb](https://github.com/CircleCI-Public/path-filtering-orb) to specify multiple configs.

**Comment by jimhartmanknc** [comment]
So I'm assuming that is why the following doesn't work
```yaml
orbs:
  path-filtering: circleci/path-filtering@1.0.0
  continuation: circleci/continuation@1.0.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          name: "updates to clients"
          base-revision: main
          config-path: .circleci/continue_config.yml
          mapping: |
            my/path/.* my-path-updated true
          filters:
            branches:
              only:
                - main

      - continuation/continue:
          name: "pass through"
          configuration_path: .circleci/continue_config.yml
          filters:
            tags:
              only:
                - /.*/
```
I need to have a workflow run only _after_ merging to main, but in all other cases, I still want tag-based workflows to run in their respective branches.
