### ISSUE TITLE
[FR] Create a solution for aggregated results

### ISSUE THREAD

**Issue by or-shachar** [CircleCI-Public/continuation-orb#15]
## Description

This continuation orb added the long-awaited support in monorepos where we have first step to evaluate "what to do", and the continue step to actually do it.

The next step to make this solution monorepos friendly is to allow nice integration with github "required" status so PRs would get green-go only if: (a) no workflows actually ran or (b) all workflows that ran actually succeeded.

The idea is that all statuses would be aggregated into a single status context in Github (since Github only allows to pre-configure the required context).

The easiest way to implement it first is to have the continue job configured to verify that all scheduled workflows actually passed and make the continuation workflow status the required one.

## Examples:

1. **Dana** opens a PR with changes to `foo` area, which is dynamically translated into `backend-build` workflow. Her PR required check is `backend-build`
2. **Bekah** opens a PR with changes to `bar` area, which is dynamically translated into `frontend-build` workflow. Her PR required check is `frontend-build`
3. **John** opens a PR to `protos` area, which is dyanmically translated into `protobuf-build`, `backend-build` and `frontend-build` workflows. His PR required checks are all three workflows.

We can extend the `continue` job with the following syntax:
```yaml
    jobs:
      - continuation/continue:
          configuration_path: ./cont-config.yml
          propagate: true  # waits for downstream builds and propagate their aggregated statuses
```

Another advanced option:
```yaml
    jobs:
      - continuation/continue:
          configuration_path: ./cont-config.yml
          propagate_name_patterns: ["required-.*"]  # waits for downstream workflows with name that matches one of the given patterns, and propagate their aggregated statuses
```

## Supporting Documentation Links:

https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging
