### ISSUE TITLE
Expose `when` option as a parameter

### ISSUE THREAD

**Issue by sidpalas** [CircleCI-Public/continuation-orb#20]
## Describe Request:

I would like to be able to optionally use the continuation orb with `when: on_fail`.

The use case I have in mind is to kick of a `manual approval` override in the case of a failed job:
```
workflows:
  approve_manual_override:
    jobs:
      - manual-step-if-jobs-failed:
          type: approval
```
and/or kick off different downstream workflows depending if a particular job succeeded or failed.

I have this working in my codebase by copying the source of the orb as a command in my `config.yml` but would love for this to be incorporated into the upstream orb!

## Examples:

New parameter:
```
      when:
        description: When to run the workflow ['on_fail', 'on_success']
        type: string
        default: 'on_success'
```

Usage:
```
    steps:
      - run:
          when: << parameters.when >>
```
