### ISSUE TITLE
Request: how to dynamically select whether to continue

### ISSUE THREAD

**Issue by danopia** [CircleCI-Public/continuation-orb#6]
## Describe Request:

I am generating a new CircleCI configuration file to give to this orb:

```
      - continuation/continue:
          configuration_path: ".circleci/continue_config.yml"
```

Unfortunately, sometimes there are simply no workflows that I'd want to continue into. For example, a PR that only updates README.md will not match any entries in my mapping for `path-filtering-orb`. In this case CircleCI considers the continued build an error because there is nothing to do:

<img width="560" alt="Screenshot 2021-04-01 at 13 59 24" src="https://user-images.githubusercontent.com/40628/113290898-8a011600-92f2-11eb-9691-a4e5eeb30005.png">

In this case the documentation says to close out:

```
      - continuation/finish
```

These are two different steps - I'm not aware of how to conditionally call steps based on the output of a previous step!

It seems as though this orb should have a third command that can dynamically switch between 'continue' or 'finish' depending on a parameter.

## Examples:

Something like this could probably work, if nothing else:

```yaml
      - run:
          command: echo 'export CONTINUATION_ACTION=continue' >> $BASH_ENV
      - continuation/decide:
          configuration_path: ".circleci/continue_config.yml"
          action: $CONTINUATION_ACTION
```

I could also imagine there being a special check on the config on disk, for example if `.circleci/continue_config.yml` is empty (zero bytes) then finish instead of continuing.

## Supporting Documentation Links:

* https://github.com/CircleCI-Public/api-preview-docs/blob/path-filtering/docs/setup-workflows.md
